name: Web Automation CI with Allure

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn clean test
        working-directory: web-automation-bdd

      - name: Generate Allure Report
        run: mvn allure:report
        working-directory: web-automation-bdd

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: web-automation-bdd/target/site/allure-maven-plugin
