name: CI with Allure Report

on:
  pull_request:
    branches: [main]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Run tests and generate Allure results
        run: mvn clean test

      - name: Generate Allure report
        run: |
          mkdir -p target/allure-report
          npx allure generate target/allure-results --clean -o target/allure-report

      - name: Deploy Allure report to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report
          publish_branch: gh-pages
          commit_message: "Update Allure report [skip ci]"
