name: CI with Allure Report

on:
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Load previous Allure history
        id: history
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Run tests
        run: mvn clean test

      - name: Generate Allure report
        uses: andgineer/allure-report@v3.6
        id: allure
        with:
          allure-results: target/allure-results
          website: gh-pages
          reports-site-path: allure-history

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ steps.allure.outputs.reports-site }}
          destination_dir: ${{ steps.allure.outputs.reports-site-path }}
          keep_files: true
